#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

# Learn more at https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings

title            : Donnons du sens physique à nos équations  # The title of the book 
author           : Emeline Faugere, ENS Paris-Saclay  # The author of the book
copyright        : "2025"  # Copyright year to be placed in the footer
logo             : ressources/img/image_titre.png  # A path to the book logo
exclude_patterns : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", README.md]

#######################################################################################
# Execution settings

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks  : force  # Whether to execute notebooks at build time. 
                              # Must be one of ("auto", "force", "cache", "off")
  cache              : ""     # A path to the jupyter cache that will be used to store execution artifacts. 
                              # Defaults to `_build/.jupyter_cache/`
  exclude_patterns   : []     # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout            : 30     # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp        : false  # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                              # otherwise the notebook's parent directory will be the cwd.
  allow_errors       : false  # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output      : show   # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# LaTeX-specific settings
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname          : M1_SPA.tex
  latex_engine          : pdflatex # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex : true # use sphinx-jupyterbook-latex for pdf builds as default


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


#######################################################################################
# HTML-specific settings
html:
  favicon                   : ressources/img/favicon.png  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  use_multitoc_numbering    : false  # Continuous numbering across parts/chapters
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  analytics                 : {}
  static_path               : _static #ajouté pour les pdf

  comments:
    hypothesis              : true
    utterances              : false
  announcement              : "" # A banner announcement at the top of the site.

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :  # A list of extra extensions to load by Sphinx (added to those already used by JB).
    - sphinx_jupyterbook_latex
    - sphinx_proof
    # config:
    #   jblatex_load_imgconverter: true
    #   jblatex_captions_to_parts: true
    
  local_extensions          :   # A list of local extensions to load by sphinx specified by "name: path" items
  recursive_update          : false # A boolean indicating whether to overwrite the Sphinx config (true) or recursively update (false)
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
    language: fr
    latex_elements:  # see https://www.sphinx-doc.org/en/master/latex.html
      papersize: 'a4paper'
      preamble:  '\usepackage{bm} \usepackage{enumitem} \setitemize[0]{label=\textbullet} \usepackage{tikz} \usetikzlibrary {automata,positioning}'
      html_extra_path: ["_static"] #ajouté pour les pdf

      
#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

# Information about where the book exists on the web
repository:
  url                       : https://github.com/executablebooks/jupyter-book  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links
